name: First Workflow
on:
  push: 
     branches:
       - main 

jobs:
  example-job:
    runs-on: ubuntu-24.04

    steps:
      - name: print welcome message
        run: echo "Welcome message from hakam"

      - name: checout repository  
        uses: actions/checkout@v7.0.0

      - name: list repository  
        run: ls -lha 
         
